### ISSUE TITLE
thiếu nhiều trường trong model để giải quyết yêu cầu gọi thông tin từ front-end

### ISSUE THREAD

**Issue by Vu-nh1109** [IK32K3/MovieTicket-BE#2]
Trước hết thiếu trường actor, director, language, rated, trailer trong movie. 
Link tham khảo api: https://docs.google.com/document/d/1GFluNkNNZQH1fWSYVoClWOT2F2bucAoCvq7mxfewbcw/edit?tab=t.0

Ngoài ra, front-end muốn tìm showtime với trường location = Hanoi thì có nên thêm trường này vào cinemas không (nếu không sẽ phải giải quyết chuỗi từ string address)

**Comment by IK32K3** [comment]
Đã update thêm trường. Còn ở showtime sẽ thêm id của rạp sẽ chiếu nó
